import {library} from "@fortawesome/fontawesome-svg-core";
import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";
import {faPepperHot,
	faBell as faBellSolid ,
	faComments,
	faSliders,
	faUser,
	faRightFromBracket,
	faXmark,
	faCirclePlus,
	faCircleMinus,
	faChevronRight,
	faChevronUp,
	faChevronDown,
	faCheck,
	faCircle,
	faGear,
	faPencil,
	faBolt,
	faPlus,
	faHeart,
	faLocationDot,
	faCircleInfo,
	faArrowDown,
	faQuoteRight,
	faVenusMars,
	faEye,
	faShapes,
	faChevronLeft,
	faEllipsis,
	faPercent,
} from "@fortawesome/free-solid-svg-icons";
import {faBell as faBellRegular} from "@fortawesome/free-regular-svg-icons";


library.add(
	faPepperHot,
	faBellSolid,
	faBellRegular,
	faComments,
	faSliders,
	faUser,
	faRightFromBracket,
	faXmark,
	faCirclePlus,
	faCircleMinus,
	faChevronRight,
	faChevronUp,
	faChevronDown,
	faCheck,
	faCircle,
	faGear,
	faPencil,
	faBolt,
	faPlus,
	faHeart,
	faLocationDot,
	faCircleInfo,
	faArrowDown,
	faQuoteRight,
	faVenusMars,
	faEye,
	faShapes,
	faChevronLeft,
	faPercent,
	faEllipsis,
);

export {FontAwesomeIcon};